### PR TITLE
Helix 5 migration

### PR DESCRIPTION
**Pull request by jindaliiita**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after), along with a short summary of changes:

## Issue

Fixes 

## Changelog:
_Please enter each change as a new bullet point_

## Test URLs:
- Original: https://www.sunstar.com
- Before: https://main--sunstar--sunstar-global.hlx.live
- After: https://helix-5-migration--sunstar--sunstar-global.hlx.live

## Library

- [ ] New Blocks introduced in this PR
      If yes, please provide details below
**Block Name** : For e.g. _cards_
- [x] Documented in sidekick library

- [ ] New variations introduced in this PR
**Variation Name** :  For e.g. _cards (grid)_
- [ ] Documented in sidekick library

- [ ] New mixins introduced in this PR
**Mixin Name** :  For e.g. _compact, white_
- [ ] Documented in sidekick library

### CODE REVIEW

**Comment by jindaliiita** [comment]
The lint issue was already present before. There is no issue in the files that I have changed.
https://github.com/sunstar-global/sunstar/actions/runs/12117980264/job/33781539083?pr=81

**Review by sdmcraft — COMMENTED** [review]
Thanks @jindaliiita .
I guess, we'd need a few other changes outside of this:
- Set form submission flow in Sharepoint side (@ehrro's help would be needed)
- Update the BYODNS mappings

**Comment by sdmcraft** [comment]
Unrelated to pr but looks like linting issues have cropped in since we went live.

**Comment by jindaliiita** [comment]
> Thanks @jindaliiita . I guess, we'd need a few other changes outside of this:
> 
> * Set form submission flow in Sharepoint side (@ehrro's help would be needed)
> * Update the BYODNS mappings

@sdmcraft The form submission flow has already been added by us on Power Automate.
The discussion regarding that is ongoing in Slack.
And Yes, BYODNS mappings will be changed after this PR is merged.

**Comment by jindaliiita** [comment]
> Unrelated to pr but looks like linting issues have cropped in since we went live.

Yes, its failiing because of changes done by @ehrro.
@ehrro Can you please check the lint issues reported [here](https://github.com/sunstar-global/sunstar/actions/runs/12117980264/job/33781539083?pr=81)

**Review by bosschaert — APPROVED** [review]

**Comment by ehrro** [comment]
Hello @jindaliiita will push this PR and the PR to solve the linting issues after.

**Review by ehrro — APPROVED** [review]

**Pull request merged**
