### PR TITLE
Linkedin pixel

### LINKED ISSUE #54: Add LinkedIn Pixel
Team can someone help me to integrate the LinkedIn Pixel on Sunstar.com?

Here is code.

```javascript
<script type="text/javascript">
_linkedin_partner_id = "6858425";
window._linkedin_data_partner_ids = window._linkedin_data_partner_ids || [];
window._linkedin_data_partner_ids.push(_linkedin_partner_id);
</script><script type="text/javascript">
(function(l) {
if (!l){window.lintrk = function(a,b){window.lintrk.q.push([a,b])};
window.lintrk.q=[]}
var s = document.getElementsByTagName("script")[0];
var b = document.createElement("script");
b.type = "text/javascript";b.async = true;
b.src = "https://snap.licdn.com/li.lms-analytics/insight.min.js";
s.parentNode.insertBefore(b, s);})(window.lintrk);
</script>
<noscript>
<img height="1" width="1" style="display:none;" alt="" src="https://px.ads.linkedin.com/collect/?pid=6858425&fmt=gif" />
</noscript>
```

@bosschaert @sdmcraft @meejain @JiangLong2019 @jindaliiita

### PR DESCRIPTION
**Pull request by JiangLong2019**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after), along with a short summary of changes:

## Issue

Fixes #54 

## Changelog:
_Please enter each change as a new bullet point_

## Test URLs:
- Original: https://www.sunstar.com/
- Before: https://main--sunstar--sunstar-global.hlx.live/
- After: https://linkedinpixel--sunstar--sunstar-global.hlx.live/

### CODE REVIEW

**Comment by JiangLong2019** [comment]
@ehrro I added the Linkedin Pixel function and could find it loaded after consent management, please review.

image

**Comment by ehrro** [comment]
Hello @JiangLong2019 ,

It looks like the linkedin cookies are loaded before the consent.

image

**Review by ehrro — CHANGES_REQUESTED** [review]
Script loading before consent.

image

**Comment by JiangLong2019** [comment]
@ehrro Umm, the loading order of javascript doesn't have any problem. But seems consent management needs a little bit of time for rendering and Linked pixel runs during that time.

**Pull request merged**
